### PR TITLE
Merge from upstream

### PR DESCRIPTION
**Pull request by illusional**
- No conflicts, all auto merged

### CODE REVIEW

**Review by vivbak — APPROVED** [review]
@jmarshall, I've approved this, but give a shout if you were still reviewing.

**Comment by jmarshall** [comment]
I am still reviewing this. There are only two local CPG commits, so IMHO it would be better to do this by rebasing our branch (which I have in progress) rather than merging.

**Comment by illusional** [comment]
Can we rebase with our merge permissions - or do you need to force push it to main?

**Comment by jmarshall** [comment]
Check out PR #4, which shows the rebase along with a few code tweaks to fix the linting (and just avoid some linting so our patches stay easier to reapply) and avoid reformatting so that `git diff -w origin/main..` clearly shows only the actual changes.

We would indeed need to force-push to get our **main** to point to this. PR #4 suggests perhaps using a different branch in future, so we wouldn't need to force-push this time. However we would next time we rebased anyway.

**Comment by jmarshall** [comment]
Superseded by PR #4.

**Pull request closed without merging**
